package com.omiphane.generator.dao;

import com.omiphane.generator.model.ColumnDefine;
import com.omiphane.generator.model.ColumnDefineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ColumnDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_define
     *
     * @mbggenerated
     */
    int countByExample(ColumnDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_define
     *
     * @mbggenerated
     */
    int deleteByExample(ColumnDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_define
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_define
     *
     * @mbggenerated
     */
    int insert(ColumnDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_define
     *
     * @mbggenerated
     */
    int insertSelective(ColumnDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_define
     *
     * @mbggenerated
     */
    List<ColumnDefine> selectByExample(ColumnDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_define
     *
     * @mbggenerated
     */
    ColumnDefine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_define
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ColumnDefine record, @Param("example") ColumnDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_define
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ColumnDefine record, @Param("example") ColumnDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_define
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ColumnDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_define
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ColumnDefine record);
}