package com.omiphane.generator.dao;

import com.omiphane.generator.model.DeviceBase;
import com.omiphane.generator.model.DeviceBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_base
     *
     * @mbggenerated
     */
    int countByExample(DeviceBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_base
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_base
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_base
     *
     * @mbggenerated
     */
    int insert(DeviceBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_base
     *
     * @mbggenerated
     */
    int insertSelective(DeviceBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_base
     *
     * @mbggenerated
     */
    List<DeviceBase> selectByExample(DeviceBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_base
     *
     * @mbggenerated
     */
    DeviceBase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_base
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceBase record, @Param("example") DeviceBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_base
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceBase record, @Param("example") DeviceBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_base
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_base
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceBase record);
}