package com.omiphane.generator.dao;

import com.omiphane.generator.model.DeviceReal;
import com.omiphane.generator.model.DeviceRealExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceRealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_real
     *
     * @mbggenerated
     */
    int countByExample(DeviceRealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_real
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceRealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_real
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_real
     *
     * @mbggenerated
     */
    int insert(DeviceReal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_real
     *
     * @mbggenerated
     */
    int insertSelective(DeviceReal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_real
     *
     * @mbggenerated
     */
    List<DeviceReal> selectByExample(DeviceRealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_real
     *
     * @mbggenerated
     */
    DeviceReal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_real
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceReal record, @Param("example") DeviceRealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_real
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceReal record, @Param("example") DeviceRealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_real
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceReal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_real
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceReal record);
}