package com.omiphane.generator.dao;

import com.omiphane.generator.model.DeviceData;
import com.omiphane.generator.model.DeviceDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_data
     *
     * @mbggenerated
     */
    int countByExample(DeviceDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_data
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_data
     *
     * @mbggenerated
     */
    int insert(DeviceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_data
     *
     * @mbggenerated
     */
    int insertSelective(DeviceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_data
     *
     * @mbggenerated
     */
    List<DeviceData> selectByExample(DeviceDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_data
     *
     * @mbggenerated
     */
    DeviceData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceData record, @Param("example") DeviceDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceData record, @Param("example") DeviceDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceData record);
}