package com.omiphane.generator.model;

public class ColumnDefine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_define.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_define.column_type
     *
     * @mbggenerated
     */
    private Integer columnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_define.data_index
     *
     * @mbggenerated
     */
    private String dataIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_define.text
     *
     * @mbggenerated
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_define.id
     *
     * @return the value of column_define.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_define.id
     *
     * @param id the value for column_define.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_define.column_type
     *
     * @return the value of column_define.column_type
     *
     * @mbggenerated
     */
    public Integer getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_define.column_type
     *
     * @param columnType the value for column_define.column_type
     *
     * @mbggenerated
     */
    public void setColumnType(Integer columnType) {
        this.columnType = columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_define.data_index
     *
     * @return the value of column_define.data_index
     *
     * @mbggenerated
     */
    public String getDataIndex() {
        return dataIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_define.data_index
     *
     * @param dataIndex the value for column_define.data_index
     *
     * @mbggenerated
     */
    public void setDataIndex(String dataIndex) {
        this.dataIndex = dataIndex == null ? null : dataIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_define.text
     *
     * @return the value of column_define.text
     *
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_define.text
     *
     * @param text the value for column_define.text
     *
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}