package com.omiphane.generator.model;

public class DeviceBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_base.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_base.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_base.device_name
     *
     * @mbggenerated
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_base.device_typ
     *
     * @mbggenerated
     */
    private Byte deviceTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_base.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_base.id
     *
     * @return the value of device_base.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_base.id
     *
     * @param id the value for device_base.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_base.device_id
     *
     * @return the value of device_base.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_base.device_id
     *
     * @param deviceId the value for device_base.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_base.device_name
     *
     * @return the value of device_base.device_name
     *
     * @mbggenerated
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_base.device_name
     *
     * @param deviceName the value for device_base.device_name
     *
     * @mbggenerated
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_base.device_typ
     *
     * @return the value of device_base.device_typ
     *
     * @mbggenerated
     */
    public Byte getDeviceTyp() {
        return deviceTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_base.device_typ
     *
     * @param deviceTyp the value for device_base.device_typ
     *
     * @mbggenerated
     */
    public void setDeviceTyp(Byte deviceTyp) {
        this.deviceTyp = deviceTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_base.nick_name
     *
     * @return the value of device_base.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_base.nick_name
     *
     * @param nickName the value for device_base.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }
}