package com.omiphane.generator.model;

public class DeviceData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_data.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_data.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_data.prop_enum
     *
     * @mbggenerated
     */
    private Integer propEnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_data.prop_data
     *
     * @mbggenerated
     */
    private String propData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_data.json_data
     *
     * @mbggenerated
     */
    private String jsonData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_data.id
     *
     * @return the value of device_data.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_data.id
     *
     * @param id the value for device_data.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_data.device_id
     *
     * @return the value of device_data.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_data.device_id
     *
     * @param deviceId the value for device_data.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_data.prop_enum
     *
     * @return the value of device_data.prop_enum
     *
     * @mbggenerated
     */
    public Integer getPropEnum() {
        return propEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_data.prop_enum
     *
     * @param propEnum the value for device_data.prop_enum
     *
     * @mbggenerated
     */
    public void setPropEnum(Integer propEnum) {
        this.propEnum = propEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_data.prop_data
     *
     * @return the value of device_data.prop_data
     *
     * @mbggenerated
     */
    public String getPropData() {
        return propData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_data.prop_data
     *
     * @param propData the value for device_data.prop_data
     *
     * @mbggenerated
     */
    public void setPropData(String propData) {
        this.propData = propData == null ? null : propData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_data.json_data
     *
     * @return the value of device_data.json_data
     *
     * @mbggenerated
     */
    public String getJsonData() {
        return jsonData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_data.json_data
     *
     * @param jsonData the value for device_data.json_data
     *
     * @mbggenerated
     */
    public void setJsonData(String jsonData) {
        this.jsonData = jsonData == null ? null : jsonData.trim();
    }
}