package com.omiphane.generator.model;

public class DeviceReal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_real.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_real.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_real.speed
     *
     * @mbggenerated
     */
    private Integer speed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_real.weight
     *
     * @mbggenerated
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_real.latitude
     *
     * @mbggenerated
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_real.longtitude
     *
     * @mbggenerated
     */
    private Double longtitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_real.user_data
     *
     * @mbggenerated
     */
    private String userData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_real.parameter
     *
     * @mbggenerated
     */
    private String parameter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_real.id
     *
     * @return the value of device_real.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_real.id
     *
     * @param id the value for device_real.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_real.device_id
     *
     * @return the value of device_real.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_real.device_id
     *
     * @param deviceId the value for device_real.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_real.speed
     *
     * @return the value of device_real.speed
     *
     * @mbggenerated
     */
    public Integer getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_real.speed
     *
     * @param speed the value for device_real.speed
     *
     * @mbggenerated
     */
    public void setSpeed(Integer speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_real.weight
     *
     * @return the value of device_real.weight
     *
     * @mbggenerated
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_real.weight
     *
     * @param weight the value for device_real.weight
     *
     * @mbggenerated
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_real.latitude
     *
     * @return the value of device_real.latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_real.latitude
     *
     * @param latitude the value for device_real.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_real.longtitude
     *
     * @return the value of device_real.longtitude
     *
     * @mbggenerated
     */
    public Double getLongtitude() {
        return longtitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_real.longtitude
     *
     * @param longtitude the value for device_real.longtitude
     *
     * @mbggenerated
     */
    public void setLongtitude(Double longtitude) {
        this.longtitude = longtitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_real.user_data
     *
     * @return the value of device_real.user_data
     *
     * @mbggenerated
     */
    public String getUserData() {
        return userData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_real.user_data
     *
     * @param userData the value for device_real.user_data
     *
     * @mbggenerated
     */
    public void setUserData(String userData) {
        this.userData = userData == null ? null : userData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_real.parameter
     *
     * @return the value of device_real.parameter
     *
     * @mbggenerated
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_real.parameter
     *
     * @param parameter the value for device_real.parameter
     *
     * @mbggenerated
     */
    public void setParameter(String parameter) {
        this.parameter = parameter == null ? null : parameter.trim();
    }
}