package com.omiphane.generator.model;

public class enumDefine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_define.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_define.enum_value
     *
     * @mbggenerated
     */
    private Integer enumValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_define.enum_name
     *
     * @mbggenerated
     */
    private String enumName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_define.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_define.id
     *
     * @return the value of enum_define.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enum_define.id
     *
     * @param id the value for enum_define.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_define.enum_value
     *
     * @return the value of enum_define.enum_value
     *
     * @mbggenerated
     */
    public Integer getEnumValue() {
        return enumValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enum_define.enum_value
     *
     * @param enumValue the value for enum_define.enum_value
     *
     * @mbggenerated
     */
    public void setEnumValue(Integer enumValue) {
        this.enumValue = enumValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_define.enum_name
     *
     * @return the value of enum_define.enum_name
     *
     * @mbggenerated
     */
    public String getEnumName() {
        return enumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enum_define.enum_name
     *
     * @param enumName the value for enum_define.enum_name
     *
     * @mbggenerated
     */
    public void setEnumName(String enumName) {
        this.enumName = enumName == null ? null : enumName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_define.memo
     *
     * @return the value of enum_define.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enum_define.memo
     *
     * @param memo the value for enum_define.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}