package com.omiphane.generator.model;

public class Node {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_name
     *
     * @mbggenerated
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_type
     *
     * @mbggenerated
     */
    private Integer nodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_layer
     *
     * @mbggenerated
     */
    private String nodeLayer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.is_leaf
     *
     * @mbggenerated
     */
    private String isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_icon
     *
     * @mbggenerated
     */
    private String nodeIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.id
     *
     * @return the value of node.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.id
     *
     * @param id the value for node.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.parent_id
     *
     * @return the value of node.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.parent_id
     *
     * @param parentId the value for node.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_name
     *
     * @return the value of node.node_name
     *
     * @mbggenerated
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.node_name
     *
     * @param nodeName the value for node.node_name
     *
     * @mbggenerated
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_type
     *
     * @return the value of node.node_type
     *
     * @mbggenerated
     */
    public Integer getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.node_type
     *
     * @param nodeType the value for node.node_type
     *
     * @mbggenerated
     */
    public void setNodeType(Integer nodeType) {
        this.nodeType = nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_layer
     *
     * @return the value of node.node_layer
     *
     * @mbggenerated
     */
    public String getNodeLayer() {
        return nodeLayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.node_layer
     *
     * @param nodeLayer the value for node.node_layer
     *
     * @mbggenerated
     */
    public void setNodeLayer(String nodeLayer) {
        this.nodeLayer = nodeLayer == null ? null : nodeLayer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.is_leaf
     *
     * @return the value of node.is_leaf
     *
     * @mbggenerated
     */
    public String getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.is_leaf
     *
     * @param isLeaf the value for node.is_leaf
     *
     * @mbggenerated
     */
    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf == null ? null : isLeaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_icon
     *
     * @return the value of node.node_icon
     *
     * @mbggenerated
     */
    public String getNodeIcon() {
        return nodeIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.node_icon
     *
     * @param nodeIcon the value for node.node_icon
     *
     * @mbggenerated
     */
    public void setNodeIcon(String nodeIcon) {
        this.nodeIcon = nodeIcon == null ? null : nodeIcon.trim();
    }
}